In [13]:
# CMPE 442: Machine Learning
# Assignment: 2
# Question: 1
# Author: Efe Berk ERGULEC

In [14]:
# Implementing Libraries
import csv
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import collections
from sklearn.metrics import *
import random

In [15]:
'''Functions that I will use during this question'''
# Loads CSV file
def load_CSV_file(file):
    with open(file) as csv_file:
        csv_array = csv.reader(csv_file, delimiter=',')
        line_count = 0
        data = []
        for row in csv_array:
            data.append([])
            if line_count == 0:
                line_count += 1
            else:
                for i in range(len(row)):
                    data[line_count - 1].append(row[i])
                line_count += 1
    return data;

# Splits dataset into training and test data
def split_dataset(dataset):
    s, ve, vi = np.array(dataset[0:50]), np.array(dataset[50:100]), np.array(dataset[100:150])
    a = 49
    s_tr = []
    for i in range(40):
        s_tr.append([])
        k = random.randint(0,a)
        for j in range(5):
            s_tr[i].append(s[k][j])
        a -= 1
        np.delete(s, k)
    s_te = []
    for i in range(10):
        s_te.append([])
        for j in range(5):
            s_te[i].append(s[i][j])
    a = 49
    ve_tr = []
    for i in range(40):
        ve_tr.append([])
        k = random.randint(0,a)
        for j in range(5):
            ve_tr[i].append(ve[k][j])
        a -= 1
        np.delete(s, k)
    ve_te = []
    for i in range(10):
        ve_te.append([])
        for j in range(5):
            ve_te[i].append(ve[i][j])
    a = 49
    vi_tr = []
    for i in range(40):
        vi_tr.append([])
        k = random.randint(0,a)
        for j in range(5):
            vi_tr[i].append(vi[k][j])
        a -= 1
        np.delete(s, k)
    vi_te = []
    for i in range(10):
        vi_te.append([])
        for j in range(5):
            vi_te[i].append(vi[i][j])
    s_tr = np.array(s_tr)
    s_te = np.array(s_te)
    ve_tr = np.array(ve_tr)
    ve_te = np.array(ve_te)
    vi_tr = np.array(vi_tr)
    vi_te = np.array(vi_te)
    return s_tr, s_te, ve_tr, ve_te, vi_tr, vi_te

# Calculates Prior Probabilities
def pre_prob(y):
    pre_probab = np.array([0,0,0])
    for i in range(len(y)):
        j = int(y[i])
        if j == 0:
            pre_probab[0] += 1
        elif j == 1:
            pre_probab[1] += 1
        else:
            pre_probab[2] += 1
    pre_probab = np.around(np.true_divide(pre_probab, len(y)), decimals = 2)
    return pre_probab

# Computes mean
def compute_mean(arr):
    c = 0
    for i in arr:
        c += float(i)
    return (c / len(arr))

# Computes Variance
def compute_variance(arr):
    mn = 9999999.0
    mx = 0.0
    for i in arr:
        if float(i) > mx:
            mx = float(i)
        elif float(i) < mn:
            mn = float(i)
    return mx - mn

# Returns mean and variance of each class as an array
def mean_var(setosa_train, versicolor_train, virginica_train):
    # Setosa
    mean = []
    mean.append([])
    variance = []
    variance.append([])
    setosa_sepallength_mean = np.around(compute_mean(setosa_train[:,0]), decimals = 2)
    setosa_sepallength_variance = np.around(compute_variance(setosa_train[:,0]), decimals = 2)
    setosa_sepalwidth_mean = np.around(compute_mean(setosa_train[:,1]), decimals = 2)
    setosa_sepalwidth_variance = np.around(compute_variance(setosa_train[:,1]), decimals = 2)
    setosa_petallength_mean = np.around(compute_mean(setosa_train[:,2]), decimals = 2)
    setosa_petallength_variance = np.around(compute_variance(setosa_train[:,2]), decimals = 2)
    setosa_petalwidth_mean = np.around(compute_mean(setosa_train[:,3]), decimals = 2)
    setosa_petalwidth_variance = np.around(compute_variance(setosa_train[:,3]), decimals = 2)
    
    mean[0].append(setosa_sepallength_mean)
    mean[0].append(setosa_sepalwidth_mean)
    mean[0].append(setosa_petallength_mean)
    mean[0].append(setosa_petalwidth_mean)
    variance[0].append(setosa_sepallength_variance)
    variance[0].append(setosa_sepalwidth_variance)
    variance[0].append(setosa_petallength_variance)
    variance[0].append(setosa_petalwidth_variance)
    
    # Versicolor
    mean.append([])
    variance.append([])
    versicolor_sepallength_mean = np.around(compute_mean(versicolor_train[:,0]), decimals = 2)
    versicolor_sepallength_variance = np.around(compute_variance(versicolor_train[:,0]), decimals = 2)
    versicolor_sepalwidth_mean = np.around(compute_mean(versicolor_train[:,1]), decimals = 2)
    versicolor_sepalwidth_variance = np.around(compute_variance(versicolor_train[:,1]), decimals = 2)
    versicolor_petallength_mean = np.around(compute_mean(versicolor_train[:,2]), decimals = 2)
    versicolor_petallength_variance = np.around(compute_variance(versicolor_train[:,2]), decimals = 2)
    versicolor_petalwidth_mean = np.around(compute_mean(versicolor_train[:,3]), decimals = 2)
    versicolor_petalwidth_variance = np.around(compute_variance(versicolor_train[:,3]), decimals = 2)
    
    mean[1].append(versicolor_sepallength_mean)
    mean[1].append(versicolor_sepalwidth_mean)
    mean[1].append(versicolor_petallength_mean)
    mean[1].append(versicolor_petalwidth_mean)
    variance[1].append(versicolor_sepallength_variance)
    variance[1].append(versicolor_sepalwidth_variance)
    variance[1].append(versicolor_petallength_variance)
    variance[1].append(versicolor_petalwidth_variance)

    # Virginica
    mean.append([])
    variance.append([])
    virginica_sepallength_mean = np.around(compute_mean(virginica_train[:,0]), decimals = 2)
    virginica_sepallength_variance = np.around(compute_variance(virginica_train[:,0]), decimals = 2)
    virginica_sepalwidth_mean = np.around(compute_mean(virginica_train[:,1]), decimals = 2)
    virginica_sepalwidth_variance = np.around(compute_variance(virginica_train[:,1]), decimals = 2)
    virginica_petallength_mean = np.around(compute_mean(virginica_train[:,2]), decimals = 2)
    virginica_petallength_variance = np.around(compute_variance(virginica_train[:,2]), decimals = 2)
    virginica_petalwidth_mean = np.around(compute_mean(virginica_train[:,3]), decimals = 2)
    virginica_petalwidth_variance = np.around(compute_variance(virginica_train[:,3]), decimals = 2)
    
    mean[2].append(virginica_sepallength_mean)
    mean[2].append(virginica_sepalwidth_mean)
    mean[2].append(virginica_petallength_mean)
    mean[2].append(virginica_petalwidth_mean)
    variance[2].append(virginica_sepallength_variance)
    variance[2].append(virginica_sepalwidth_variance)
    variance[2].append(virginica_petallength_variance)
    variance[2].append(virginica_petalwidth_variance)
    
    mean = np.array(mean)
    variance = np.array(variance)
    
    return mean, variance

# Returns posterior probability
def prob_feature_class(m, v, x):
    n_features = m.shape[1]
    pfc = np.ones(3)
    for i in range(0, 3):
        product = 1
        for j in range(0, n_features):
            product = product * (1/np.sqrt(2*3.14*v[i][j])) * np.exp(-0.5
                                 * pow((x[j] - m[i][j]),2)/v[i][j])
        pfc[i] = product
    return pfc

def find_accuracy(test, prediction):
    c = 0
    for i in range(len(test)):
        if test[i] == prediction[i]:
            c += 1
    return c / len(test)

In [16]:
# Loads dataset, splits training and test data for each class and keeps training and test data into arrays.
dataset = load_CSV_file('iris.csv')
setosa_train, setosa_test, versicolor_train, versicolor_test, virginica_train, virginica_test = split_dataset(dataset)
train_data = np.concatenate((setosa_train, versicolor_train, virginica_train), axis = 0)
test_data = np.concatenate((setosa_test, versicolor_test, virginica_test), axis = 0)

In [17]:
# Prepares training data, calculate mean, variance of all classes of all features
X_train = np.array(train_data[:, [0,1,2,3]])
y_train = np.array(train_data[:, 4])

values = {0: "Iris-setosa", 1: "Iris-versicolor", 2: "Iris-virginica"}

for i in range(0,y_train.shape[0]):
    if y_train[i] == "Iris-setosa":
        y_train[i] = int(0)
    elif y_train[i] == "Iris-versicolor":
        y_train[i] = int(1)
    else:
        y_train[i] = int(2)

# x = np.array([7.7,3.8,6.7,2.2])    # I put it here additionally, so that you can look all values specificly
X_test = np.array(test_data[:,[0,1,2,3]])   # This will be my data
y_test = np.array(test_data[:, 4])

pre_probab = pre_prob(y_train)
m, v = mean_var(setosa_train, versicolor_train, virginica_train)
predictions = []
for x in X_test:
    x = x.astype(float)
    pfc = prob_feature_class(m, v, x)
    pcf = np.ones(3)
    total_prob = 0
    for i in range(0, 3):
        total_prob = total_prob + (pfc[i] * pre_probab[i])
    for i in range(0, 3):
        pcf[i] = (pfc[i] * pre_probab[i])/total_prob
    prediction = values[int(pcf.argmax())] 
    predictions.append(prediction)

In [18]:
# Final values after all calculations (for this one it prints out last element of test data)
print("Mean = {}".format(m))                              # Output given below (mean for 3 classes of all features)
print("Variance = {}".format(v))                          # Output given below (variance for 3 classes of features)
print("Prior Probabilites = {}".format(pre_probab))       # Output given below (prior probabilities)
print("Posterior Probabilities = {}".format(pfc))         # Output given below (posterior probabilities)
print("Final Conditional Probabilities = {}".format(pcf)) # Conditional Probability of the classes given test-data
print("Prediction = {}".format(prediction))               # Output given below(final prediction)

Mean = [[4.9  3.38 1.44 0.22]
 [5.94 2.82 4.29 1.33]
 [6.56 3.   5.54 1.98]]
Variance = [[1.4 1.5 0.9 0.3]
 [1.9 1.2 1.4 0.8]
 [2.3 1.6 1.8 1. ]]
Prior Probabilites = [0.33 0.33 0.33]
Posterior Probabilities = [4.98452380e-12 1.06969714e-03 6.44826447e-03]
Final Conditional Probabilities = [6.63015330e-10 1.42285529e-01 8.57714471e-01]
Prediction = Iris-virginica


In [19]:
# Prints accuracy, classification report and confusion matrix, which you wanted us for the first question.
print("Accuracy = {}%".format(np.around(find_accuracy(y_test, predictions), decimals=4) * 100))
print(56 * '-')
print("Classification Report:")
print(classification_report(y_test, predictions, ['Iris-setosa', 'Iris-versicolor', 'Iris-virginica']))
print(56 * '-')
print("Confusion Matrix:")
print(confusion_matrix(y_test, predictions, ['Iris-setosa', 'Iris-versicolor', 'Iris-virginica']))

Accuracy = 93.33%
--------------------------------------------------------
Classification Report:
                 precision    recall  f1-score   support

    Iris-setosa       1.00      1.00      1.00        10
Iris-versicolor       0.83      1.00      0.91        10
 Iris-virginica       1.00      0.80      0.89        10

    avg / total       0.94      0.93      0.93        30

--------------------------------------------------------
Confusion Matrix:
[[10  0  0]
 [ 0 10  0]
 [ 0  2  8]]
